name: regenerate

permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'index.js'
      - 'package.json'
      - 'package-lock.json'

jobs:
  regenerate_dist-index_js:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v6
    - 
      name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
    - 
      name: regenerate dist/index.js
      run: |
        npm i -g @vercel/ncc@0.38.4
        npm install
        ncc build index.js -m
    -
      name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        file_pattern: dist/index.js
        commit_message: Regenerate dist/index.js